services:
  postgres:
    image: postgres:15
    container_name: artshop-postgres
    environment:
      POSTGRES_DB: ArtGallery
      POSTGRES_USER: maxim
      POSTGRES_PASSWORD: 654321
    ports:
      - "8000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maxim -d ArtGallery"]
      interval: 5s
      timeout: 5s
      retries: 15

  backend:
    build: .
    container_name: artshop-backend
    ports:
      - "8100:8100"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    command: >
      sh -c "
        sleep 5 &&
        java -jar app.jar
      "

  frontend:
    build: ./artshop-frontend
    container_name: artshop-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: on-failure

volumes:
  pgdata: